version: '2'
services:
    titanrest-app:
        image: titanrest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://titanrest-mysql:3306/titanrest?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    titanrest-mysql:
        extends:
            file: mysql.yml
            service: titanrest-mysql
